//
//  TestCpp.cpp
//  TestBase
//
//  Created by chengjian on 2022/1/6.
//  Copyright © 2022 chengjian. All rights reserved.
//

#include <syslog.h>
#include "TestCpp.h"
void SkDebugf(const char format[], ...) {
    va_list args;
    va_start(args, format);
    vfprintf(stderr, format, args);
    fflush(stderr);
    va_end(args);
}

void testaa() {
 
}
void testLog(){
    SkDebugf("chengjian_testLog vfprintf\n");
    printf("chengjian_testLog printf\n");
    openlog("chengjian_testLog MyMsgMARK", LOG_CONS | LOG_PID, 0);
    syslog(LOG_ERR,
            "chengjian_testLog This is a syslog test message generated by program '%s'\n",
            "ddd");
    closelog();
}
